'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Solicitud
    Public Property IdSolicitud As Integer
    Public Property idusuario As Integer
    Public Property idvacante As Integer

    Public Overridable Property Usuario As Usuario
    Public Overridable Property Vacantes As Vacantes

End Class
