'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vacantes
    Public Property IdVacante As Integer
    Public Property idcategoria As Integer
    Public Property Empresa As String
    Public Property Posicion As String
    Public Property Descripcion As String
    Public Property Horario As String
    Public Property Ubicacion As String

    Public Overridable Property Categoria As Categoria
    Public Overridable Property Solicitud As ICollection(Of Solicitud) = New HashSet(Of Solicitud)

End Class
